name: cc_signalr
description: "CC SignalR is a Flutter plugin that provides SignalR support, enabling easy management"
version: 1.1.0+2
homepage: https://github.com/codecores/cc_signalr

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  signalr_netcore: ^1.3.7
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true