name: cc_signalr
description: "CC SignalR is a Flutter plugin that provides SignalR support, enabling easy management of SignalR connections and event-driven communication. This plugin allows you to define connection options, subscribe to modules, and create custom modules to listen for specific SignalR messages, making it a powerful tool for real-time applications."
homepage: https://github.com/codecores/cc_signalr
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  signalr_netcore: ^1.3.7
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true